name: Deploy to GitHub Pages
    on:
      push:
        branches:
          - masters
    jobs:
      build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Build
          run: |
            npm ci
            npm run build
          env:
            APP_KEY: ${{ secrets.APP_KEY }}

        - name: Deploy
          uses: JamesIves/github-pages-deploy-action@releases@4.3.3
          with:
            BRANCH: gh-pages
            FOLDER: build